info:
  app:
    name: admin-service
    description: Admin Service for SHS.
    version: 1.0.0
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/adminservice
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"