info:
  app:
    name: doctor-service
    description: Doctor Service for SHS.
    version: 1.0.0
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart-healthcare-service
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"