spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user-service/**
            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/api/admin-service/**
            - id: doctor-service
              uri: lb://doctor-service
              predicates:
                - Path=/api/doctor-service/**
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/patient-service/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  secret-key: ${SECRET_KEY}