info:
  app:
    name: patient-service
    description: Patient Service for SHS.
    version: 1.0.0
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/smart-healthcare-service
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"